.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH gtali 6 "2007\-06\-09" "MATE"
.SH NAME
Tali \- A variation on poker with dice and less money.
.SH SYNOPSIS
.B gtali
.RI [ OPTION... ]
.SH DESCRIPTION
MATE Tali is a sort of poker with dice and less money.  You roll five
dice three times and try to create the best hand. Your two rerolls may
include any or all of your dice.
.SH OPTIONS
.TP
.B \-d, \-\-delay
Delay computer moves
.TP
.B \-t, \-\-thoughts
Display computer thoughts
.TP
.B \-n, \-\-computers=NUMBER
Number of computer opponents
.TP
.B \-p, \-\-humans=NUMBER
Number of human opponents
.TP
.B \-g, \-\-game=STRING
Game choice: Regular or Colours
.P
This program also accepts the standard MATE and GTK options.
.SH AUTHORS
.B gtali
was written by Scott Heavner.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "mate-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
